// <auto-generated />
namespace Faculty.Logger.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddActionDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddActionDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201709101830186_AddActionDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
